export enum ProjectType {
	RESIDENTIAL = 'RESIDENTIAL',
	COMMERCIAL = 'COMMERCIAL',
	OFFICE = 'OFFICE',
	ENTERTAINMENT = 'ENTERTAINMENT'
}

export enum ProjectStatus {
	ACTIVE = 'ACTIVE',
	COMPLETED = 'COMPLETED',
	DELETE = 'DELETE',
}

export enum ProjectStyle {
	MODERN = 'MODERN',
	MINIMAL = 'MINIMAL',
	CLASSIC = 'CLASSIC',
	TRADITIONAL = 'TRADITIONAL',
	INDUSTRIAL = 'INDUSTRIAL',
	SCANDINAVIAN = 'SCANDINAVIAN',
}
